-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."account"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    email text NOT NULL,
    hashed_password text NOT NULL,
    username text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."group"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    owner_id integer NOT NULL,
    group_name text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.review
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    grade smallint NOT NULL,
    description text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_favourite
(
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    PRIMARY KEY (user_id, movie_id)
);

CREATE TABLE IF NOT EXISTS public.group_favourite
(
    group_id integer NOT NULL,
    movie_id integer NOT NULL,
    PRIMARY KEY (group_id, movie_id)
);

CREATE TABLE IF NOT EXISTS public.group_member
(
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, group_id)
);

ALTER TABLE IF EXISTS public."group"
    ADD FOREIGN KEY (owner_id)
    REFERENCES public."account" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (user_id)
    REFERENCES public."account" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_favourite
    ADD FOREIGN KEY (user_id)
    REFERENCES public."account" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_favourite
    ADD FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_member
    ADD FOREIGN KEY (user_id)
    REFERENCES public."account" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_member
    ADD FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
