-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL,
    email text NOT NULL,
    hashed_password text NOT NULL,
    username text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movies
(
    movieid integer NOT NULL,
    PRIMARY KEY (movieid)
);

CREATE TABLE IF NOT EXISTS public."group"
(
    id integer NOT NULL,
    owner integer NOT NULL,
    group_name text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.review
(
    id integer NOT NULL,
    userid integer NOT NULL,
    movieid integer NOT NULL,
    grade smallint NOT NULL,
    description text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_favourites
(
    user_id integer NOT NULL,
    movies_movieid integer NOT NULL,
    PRIMARY KEY (user_id, movies_movieid)
);

CREATE TABLE IF NOT EXISTS public.group_favourites
(
    group_id integer NOT NULL,
    movies_movieid integer NOT NULL,
    PRIMARY KEY (group_id, movies_movieid)
);

CREATE TABLE IF NOT EXISTS public.group_member
(
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.group_join_request
(
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, group_id)
);

ALTER TABLE IF EXISTS public."group"
    ADD FOREIGN KEY (owner)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (movieid)
    REFERENCES public.movies (movieid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (userid)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_favourites
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_favourites
    ADD FOREIGN KEY (movies_movieid)
    REFERENCES public.movies (movieid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_favourites
    ADD FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_favourites
    ADD FOREIGN KEY (movies_movieid)
    REFERENCES public.movies (movieid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_member
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_member
    ADD FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_join_request
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.group_join_request
    ADD FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;